name: Terraform CI/CD

# Controls when the workflow is triggered
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install Terragrunt
    - name: Install Terragrunt
      run: |
        curl -L https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.12/terragrunt_linux_amd64 -o terragrunt
        chmod +x terragrunt
        sudo mv terragrunt /usr/local/bin/

    # Set up Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Runs test for the 'policy' module
    - name: Run policy module tests
      run: |
        cd modules/policy
        terraform init
        terraform test

    # Runs test for the 'storage' module
    - name: Run storage module tests
      run: |
        cd modules/storage
        terraform init
        terraform test

  semantic-versioning:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
          # Disable persisting credentials in the git config
          persist-credentials: false

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
